name: Keep ExoDetect Backend Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:        # allow manual run

jobs:
  ping-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Ping backend root
        run: |
          curl -s https://exodetect-backend-3.onrender.com/ > /dev/null
